exports.categories = [ 'Commutative Algebra',
  'Linear and Multilinear Algebra: Matrix Theory',
  'Nonassociative Rings and Algebras',
  'Abstract Harmonic Analysis',
  'Harmonic Analysis over Euclidian Space',
  'Functional Analysis',
  'Global Analysis, Analysis on Manifolds',
  'Numerical Analysis',
  'Associative Rings and Algebras',
  'Aproximations and Expansions',
  'Astronomy and Astrophysics',
  'Biology and other Natural Sciences',
  'Variational Calculus and Control, Optimization',
  'Computer Science',
  'Computer Science Applied to Teaching',
  'Ordinary Differential Equations',
  'Partial Differential Equations',
  'Whole Equations',
  'Functional and Differences Equations',
  'Statistics',
  'Complex Analysis',
  'Special Functions',
  'Real Functions',
  'Geophysics',
  'Geometry',
  'Algebraic Geometry',
  'Differential Geometry',
  'Discrete and Convex Geometry',
  'Topological Groups, Lie Groups',
  'History of Science',
  'Information and Communication, Circuits',
  'Operations Research',
  'K-Theory',
  'Mathematical Logic and Fundaments',
  'Teaching Mathematics',
  'Fluid Dynamics',
  'Particle and Systems Mechanics',
  'Soft Solids Mechanics',
  'Statistichal Mechanics, Structure of Matter',
  'Measure and Integration Theory',
  'Optics and Electromagnetic Theory',
  'Order, Lattices, Ordered Algebraic Structures',
  'Other',
  'Relativity and Gravitational Theory',
  'General Algebraic Systems',
  'Dynamical Systems and Ergodic Theory',
  'Sequences, Series and Additibility',
  'Quantum Theory',
  'Fields and Polynomials',
  'Category Theory: Homological Algebra',
  'Group Theory and Generalizations',
  'Game Theory, Economics and Behavioral Science',
  'Probability Theory and Stochastic Processes',
  'Number Theory',
  'Operator Theory',
  'Potential Theory',
  'Systems Theory: Control',
  'Classical Thermodynamics, Heat Transference',
  'Algebraic Topology',
  'General Topology',
  'Integral Transformations and Operational Calculus',
  'Several Complex Variables Analysis and Analytical Spaces',
  'Varieties and Celullar Complexes' ];